#!/bin/env bash

while getopts "dthw:n:c:" opt; do
  case $opt in
    w)
      WINDOW="$OPTARG"
      ;;
    n)
      WIN_NUMBER="$OPTARG"
      ;;
    t)
      USE_THIS_WINDOW=1
      ;;
    c)
      CONFIG="$OPTARG"
      ;;
    d)
      DONT_ATTACH=1
      ;;
    h)
      usage
      exit
      ;;
    ?)
      echo "Wrong argument $OPTARG"
      usage
      exit
      ;;
  esac
done

if [ -z $WINDOW ]; then
  echo "Name must be specified"
  exit 1
fi

SCRIPT_DIR=$(dirname $(readlink -f $BASH_SOURCE))
CONFIG_DIR=~/.tmunix

if [ -z "$CONFIG" ]; then
  CONFIG_FILE="$CONFIG_DIR/$WINDOW"
  if ! [[ -e "$CONFIG_FILE" ]]; then
    echo "using default config file"
    CONFIG_FILE="$CONFIG_DIR/default"
  fi
else
 CONFIG_FILE="$CONFIG_DIR/$CONFIG"
fi

if ! [[ -e "$CONFIG_FILE" ]]; then
  echo "$CONFIG_FILE not found"
  exit 2
fi

source "$SCRIPT_DIR/lib.sh"
source "$SCRIPT_DIR/dsl.sh"


SESSION_NAME=tmunix

tx-init-window
tx-set-win-number

if [[ $DONT_ATTACH != 1 ]]; then
  tx-attach
fi
