#!/bin/env bash

while getopts "thw:n:c:" opt; do
  case $opt in
    w)
      WINDOW="$OPTARG"
      ;;
    n)
      WIN_NUMBER="$OPTARG"
      ;;
    t)
      USE_THIS_WINDOW=1
      ;;
    c)
      CONFIG="$OPTARG"
      ;;
    h)
      usage
      exit
      ;;
    ?)
      echo "Wrong argument $OPTARG"
      usage
      exit
      ;;
  esac
done

if [ -z $WINDOW ]; then
  echo "Name must be specified"
  exit 1
fi

SCRIPT_DIR=$(dirname $(readlink -f $BASH_SOURCE))
CONFIG_DIR=~/.tmunix

if [ -z "$CONFIG" ]; then
  CONFIG_FILE="$CONFIG_DIR/$WINDOW"
  if ! [[ -e "$CONFIG_FILE" ]]; then
    echo "using default config file"
    CONFIG_FILE="$CONFIG_DIR/default"
  fi
else
 CONFIG_FILE="$CONFIG_DIR/$CONFIG"
fi

if ! [[ -e "$CONFIG_FILE" ]]; then
  echo "$CONFIG_FILE not found"
  exit 2
fi

source "$SCRIPT_DIR/lib.sh"


SESSION_NAME=tmunix

function find-window(){
  ACTIVE_WINDOW=`tmux-cmd list-windows | grep "^[0-9]*: $WINDOW" -m1`
  if [ $? -eq 0 ]; then
    CUR_WIN_NUMBER=`echo "$ACTIVE_WINDOW" | awk -F : '{print $1}'`
    return 0;
  else
    return 1;
  fi
}

function init-window(){
  if [ -z "$TMUX" ]; then
    if tmux-cmd has-session -t "$SESSION_NAME"; then
      # we make the target session the current one
      # (so that it's used by default)
      tmux-cmd attach -t "$SESSION_NAME" \; detach
    else
      tmux-cmd start-server \; set-option -g base-index 1 \; new-session -d -s "$SESSION_NAME"
    fi
  fi
  if ! find-window; then
    if [[ "$USE_THIS_WINDOW" -eq 1 ]]; then
      tmux-cmd rename-window "$WINDOW"
    else
      tmux-cmd new-window -n "$WINDOW"
    fi
    FIRST_RUN=true
  else
    tmux-cmd select-window -t $CUR_WIN_NUMBER
  fi

  find-window
  source "$CONFIG_FILE"
}

function attach(){
  if [ -z $TMUX ]; then
    tmux-cmd -u attach-session -t "$SESSION_NAME"
  fi
}

function set-win-number(){
  if ! [ -z $WIN_NUMBER ] && [ $WIN_NUMBER -ne $CUR_WIN_NUMBER ]; then
    tmux-cmd move-window -t $WIN_NUMBER || tmux-cmd swap-window -t $WIN_NUMBER
  fi
  find-window
}

init-window
set-win-number
attach
